# Chain ladder method

We're going to implement the most used methodology for estimating the projected losses using data from run-off triangles. 

The procedure consists on finding some factors by development year from which we could estimate the expected loss on a certein year by their next development. This is described as follows:
\begin{array}{rl}
C_{i,j+1} = f_j \times C_{i,j}.
\end{array}

Where $C_{i,j}$ represents every cell of triangles. Then, the development factor tells you how the cumulative amount in development year $j$ grows to the cumulative amount in year $j+1$. We need to find the $\hat{f}_j^{CL}$ estimated for each development year:

\begin{array}{rl}
\hat{C}_{ij}^{CL} &= C_{i,I-i} \cdot \prod_{l=I-i}^{j-1} \hat{f}_l^{CL} \\
\hat{f}_j^{CL} &= \frac{\sum_{i=1}^{I-j-1} C_{i,j+1}}{\sum_{i=1}^{I-j-1} C_{ij}},
\end{array}

Where $C_{i,I−i}$ is on the last observed diagonal. It is clear that an important assumption of the chain-ladder method is that the proportional developments of claims from one development period to the next are similar for all occurrence years.

In [3]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
import chainladder as cl
import os

In [4]:
input = pd.read_csv(os.path.normpath(os.getcwd() + os.sep + os.pardir)+"/data/ppauto_pos.csv")

In [5]:
input = input[input.DevelopmentYear <= 1997]

In [6]:
cleaning_cond = np.array(['Adriatic Ins Co', 'Aegis Grp', 'Agency Ins Co Of MD Inc',
       'Allegheny Cas Co', 'American Modern Ins Grp Inc',
       'Armed Forces Ins Exchange', 'Auto Club South Ins Co',
       'Baltica-Skandinavia Rein Co Of Amer', 'Bancinsure Inc',
       'Bell United Ins Co', 'Century-Natl Ins Co', 'Co-Operative Ins Co',
       'Consumers Ins Usa Inc', 'Cornerstone Natl Ins Co',
       'Federated Natl Ins Co', 'First Amer Ins Co',
       'Florists Mut Ins Grp', 'Harbor Ins Co', 'Homestead Ins Co',
       'Inland Mut Ins Co', 'Interstate Auto Ins Co Inc', 'Lancer Ins Co',
       'Lumber Ins Cos', 'Manhattan Re Ins Co', 'Mennonite Mut Ins Co',
       'Middle States Ins Co Inc', 'National Automotive Ins',
       'Nevada General Ins Co', 'New Jersey Citizens United Rcp Exch',
       'Nichido Fire & Marine Ins Co Ltd', 'Northwest Gf Mut Ins Co',
       'Ocean Harbor Cas Ins Co', 'Overseas Partners Us Reins Co',
       'Pacific Ind Ins Co', 'Pacific Pioneer Ins Co',
       'Pacific Specialty Ins Co', 'Penn Miller Grp',
       'Pennsylvania Mfg Asn Ins Co', 'Pioneer State Mut Ins Co',
       'Protective Ins Grp', 'San Antonio Reins Co',
       'Seminole Cas Ins Co', 'Southern Group Ind Inc',
       'Southern Mut Ins Co', 'Southland Lloyds Ins Co', 'Star Ins Grp',
       'Sterling Ins Co', 'Usauto Ins Co', 'Vanliner Ins Co',
       'Wea Prop & Cas Ins Co', 'Wellington Ins Co', 'State Farm Mut Grp', 'United Services Automobile Asn Grp',
       'US Lloyds Ins Co', 'Toa-Re Ins Co Of Amer', 'FL Farm Bureau Grp'])

In [7]:
input = input[~input.GRNAME.isin(cleaning_cond)]

After importing and cleaning data as on Initial Data Analysis was intended, we are estimating the full run-off triangles for our sample through the Chain ladder (cl) library for python, as it allows us to manage large amount of triangles and derive some relevant conclusions from this methodology.

In [8]:
auto_triangles = cl.Triangle(input, 
                             index = 'GRCODE',
                             origin="AccidentYear",
                             development="DevelopmentYear",
                             columns=["IncurLoss_B"],
                             cumulative=True)

In [9]:
auto_triangles

Triangle Summary
Valuation:          1997-12
Grain:                 OYDY
Shape:      (90, 1, 10, 10)
Index:             [GRCODE]
Columns:      [IncurLoss_B]

In [10]:
auto_model = cl.Chainladder().fit(auto_triangles)

/Users/raul/opt/miniconda3/envs/MiEntorno/lib/python3.8/site-packages/chainladder/utils/weighted_regression.py:58: RuntimeWarning: Mean of empty slice
  xp.nansum(w * x * y, axis) - xp.nansum(x * w, axis) * xp.nanmean(y, axis)
/Users/raul/opt/miniconda3/envs/MiEntorno/lib/python3.8/site-packages/chainladder/utils/weighted_regression.py:62: RuntimeWarning: Mean of empty slice
  intercept = xp.nanmean(y, axis) - slope * xp.nanmean(x, axis)


In [11]:
auto_model.full_triangle_.iloc[43]

12            24            36            48            60            72            84            96            108           120           132           9999
1988   6433.0   6452.000000   6908.000000   6437.000000   6612.000000   6703.000000   6719.000000   6718.000000   6705.000000   6704.000000   6704.000000   6704.000000
1989   8697.0   8438.000000   8515.000000   8392.000000   8428.000000   8532.000000   8643.000000   8459.000000   8483.000000   8481.734825   8481.734825   8481.734825
1990  12738.0  11754.000000  11308.000000  11260.000000  11384.000000  11294.000000  11317.000000  11296.000000  11304.187125  11302.501191  11302.501191  11302.501191
1991  13658.0  12448.000000  12312.000000  12507.000000  12281.000000  12177.000000  12027.000000  11934.134375  11942.784008  11941.002832  11941.002832  11941.002832
1992  12228.0  10932.000000  11206.000000  10688.000000  10649.000000  10624.000000  10624.000000  10541.967540  10549.608157  10548.034763  10548.034763  10548.034763
1993  13138.0  13305.000000  14017.000000  13953.000000  13759.000000  13752.309235  13752.309235  13646.121758  13656.012207  13653.975516  13653.975516  13653.975516
1994  15577.0  17912.000000  17790.000000  17594.000000  17559.500324  17550.961442  17550.961442  17415.442942  17428.065323  17425.466059  17425.466059  17425.466059
1995  15785.0  18672.000000  18297.000000  18023.847214  17988.504661  17979.757161  17979.757161  17840.927745  17853.858509  17851.195741  17851.195741  17851.195741
1996  23907.0  23613.000000  23716.987669  23362.920814  23317.108992  23305.770283  23305.770283  23125.816437  23142.577587  23139.126047  23139.126047  23139.126047
1997  23369.0  23630.120038  23734.183101  23379.859538  23334.014502  23322.667572  23322.667572  23142.583254  23159.356557  23155.902514  23155.902514  23155.902514

In [ ]:
# Results

Taking an example from the sample, this company could expect that 

In [12]:
auto_model.full_triangle_.mean(0).mean(1)

12            24            36            48            60            72            84            96            108           120           132           9999
1988   8928.460674   8959.146067   9017.730337   8990.235955   8942.696629   8759.977778   8705.044444   8674.844444   8699.855556   8724.233333   8724.233333   8724.233333
1989   9830.333333  10168.377778  10235.944444  10224.177778  10164.322222  10091.200000  10021.988889   9988.888889   9970.966667   9989.878261   9989.878261   9989.878261
1990  11540.943820  11819.359551  11857.325843  11633.955556  11599.011111  11438.600000  11357.322222  11337.411111  11333.468091  11355.001856  11355.001856  11355.001856
1991  12759.696629  12692.733333  12572.177778  12431.177778  12226.100000  12108.877778  12052.255556  12011.489518  12012.041805  12028.532427  12028.532427  12028.532427
1992  14026.077778  13449.622222  13218.844444  13086.444444  13004.655556  12865.822222  12788.276875  12749.021287  12736.814936  12768.594961  12768.594961  12768.594961
1993  15488.488889  15258.977778  15148.077778  14853.411111  14724.611111  14562.292930  14466.339361  14419.130176  14412.421145  14440.897677  14440.897677  14440.897677
1994  16643.877778  16164.044444  16030.666667  15821.444444  15690.088845  15528.106182  15434.211072  15387.993111  15372.051392  15409.451839  15409.451839  15409.451839
1995  17589.766667  17226.655556  17146.677778  16948.336363  16801.165563  16596.706916  16472.537861  16411.978267  16404.268011  16435.334047  16435.334047  16435.334047
1996  18433.088889  18185.722222  18105.867216  17905.882530  17739.214707  17523.451176  17395.998935  17332.816521  17334.834001  17380.290310  17380.290310  17380.290310
1997  19373.865169  19385.365714  19363.987959  19107.182186  18943.386720  18669.372009  18493.918876  18407.648746  18413.808669  18441.195237  18441.195237  18441.195237

In [13]:
auto_AvE = auto_triangles - auto_model.full_expectation_
auto_AvE = auto_AvE[auto_AvE.valuation <= auto_triangles.valuation_date]

In [14]:
auto_AvE.mean(0).mean(1).heatmap()

/Users/raul/opt/miniconda3/envs/MiEntorno/lib/python3.8/site-packages/chainladder/core/pandas.py:364: RuntimeWarning: Mean of empty slice
  obj.values = func(obj.values, axis=axis, *args, **kwargs)
/Users/raul/opt/miniconda3/envs/MiEntorno/lib/python3.8/site-packages/pandas/io/formats/style.py:1126: RuntimeWarning: All-NaN slice encountered
  smin = np.nanmin(s.to_numpy()) if vmin is None else vmin
/Users/raul/opt/miniconda3/envs/MiEntorno/lib/python3.8/site-packages/pandas/io/formats/style.py:1127: RuntimeWarning: All-NaN slice encountered
  smax = np.nanmax(s.to_numpy()) if vmax is None else vmax


In [15]:
class ChainLadder_manual:
    def __init__(self, tabla = pd.DataFrame(), origin = "", development = "", columns = "", index = ""):
        
        self.tabla = tabla #OK
        self.origin = origin #OK
        self.development = development #OK
        self.index = index #OK
        self.columns = columns #OK

    def Triangulos(self):
        
        # Renombrar las columnas
        datos = self.tabla.rename(columns={self.origin: "AccidentYear", self.development: "DevelopmentLag", self.columns: "IncurLoss_C",
                                          self.index: "GRCODE"})

        diccionario_todos_triangulos = {} 

        for k in datos["GRCODE"].unique():

            Filtro_datos = datos[datos["GRCODE"] == k]
        
            Triangulo_full = Filtro_datos.pivot_table(values = "IncurLoss_C", index = "AccidentYear", columns='DevelopmentLag', aggfunc="sum", margins=False)
            Triangulo_full_acumulado = Triangulo_full.copy()
            
            num_filas = Triangulo_full_acumulado.shape[0]
            num_columnas = Triangulo_full_acumulado.shape[1]

            for indice, i in enumerate(range(1,num_columnas+1)):
                Triangulo_full_acumulado[Triangulo_full.columns[indice]] = Triangulo_full[Triangulo_full.columns[0:i]].sum(axis = 1)

            Triangulo_acumulado_mitad = Triangulo_full_acumulado.copy()
            for i in range(num_filas):
                for j in range(1,i+1):
                    Triangulo_acumulado_mitad.iloc[i, -j] = None  # Puedes establecerlo en None u otro valor si lo prefieres

            factores0 = Triangulo_acumulado_mitad.sum(axis = 0) # Rojo
            factores1 = Triangulo_acumulado_mitad.sum(axis = 0)-np.flip(np.diag(np.fliplr(Triangulo_acumulado_mitad), 0)) # Azul
            factores0 = factores0[1:10]
            factores1 = factores1[0:-1]
            factores = factores0.reset_index(drop = True) / factores1.reset_index(drop = True)

            Triangulo_estimado = Triangulo_acumulado_mitad.copy()
            for i in list(reversed(range(num_filas))):
                comodin = np.diag(np.fliplr(Triangulo_acumulado_mitad), 0)[i]
                for j in range(1,i+1):
                    Triangulo_estimado.iloc[i, -j] = comodin*factores.iloc[-i+9:-j+10].prod()   # Puedes establecerlo en None u otro valor si lo prefieres

            reserva_total = sum(np.array(list(reversed(np.array(Triangulo_estimado[10]))))-np.flip(np.diag(np.fliplr(Triangulo_estimado), 0)))

            diciconario_triangulo = {'Triangulo_full':Triangulo_full, "Triangulo_full_acumulado":Triangulo_full_acumulado, 
                                     "Triangulo_acumulado_mitad":Triangulo_acumulado_mitad, "factores":factores, "Triangulo_estimado":Triangulo_estimado,
                                     "reserva_total":reserva_total}
            
            nombre = "Triangulo " + str(k)
            diccionario_todos_triangulos[nombre] = diciconario_triangulo

        return diccionario_todos_triangulos


In [16]:
resultados = ChainLadder_manual(tabla = input, origin = "AccidentYear", development = "DevelopmentLag", columns = "IncurLoss_B", index = "GRCODE")
triangulos_resultados = resultados.Triangulos()
triangulos_resultados["Triangulo 43"]["Triangulo_estimado"]

DevelopmentLag       1             2              3              4   \
AccidentYear                                                          
1988              607.0   1254.000000    1836.000000    2434.000000   
1989             2254.0   5113.000000    8092.000000   10856.000000   
1990             5843.0  13267.000000   21574.000000   30245.000000   
1991            11422.0  27515.000000   46163.000000   65258.000000   
1992            19933.0  44095.000000   72834.000000  101163.000000   
1993            24604.0  56734.000000   90309.000000  123078.000000   
1994            40735.0  84679.000000  127190.000000  168902.000000   
1995            43064.0  86769.000000  129678.000000  176876.115109   
1996            41837.0  83141.000000  129536.356828  176682.918931   
1997            44436.0  94001.898129  146457.986053  199763.410909   

DevelopmentLag             5              6              7              8   \
AccidentYear                                                                 
1988              3048.000000    3663.000000    4278.000000    4892.000000   
1989             13682.000000   16699.000000   19689.000000   22667.000000   
1990             39311.000000   48237.000000   57004.000000   65769.000000   
1991             83911.000000  102380.000000  120787.000000  139220.327475   
1992            129234.000000  156956.000000  185210.631996  213475.662433   
1993            156800.000000  191021.108081  225408.013407  259807.574011   
1994            216043.669331  263194.522383  310573.815772  357970.545978   
1995            226243.412898  275620.327984  325236.468416  374870.868883   
1996            225996.294383  275319.276628  324881.222922  374461.409305   
1997            255518.704876  311284.860592  367321.196775  423378.155792   

DevelopmentLag             9              10  
AccidentYear                                  
1988              5506.000000    6120.000000  
1989             25645.000000   28504.794769  
1990             74341.235858   82631.377306  
1991            157366.102587  174914.738073  
1992            241299.769965  268208.244131  
1993            293670.515549  326419.098285  
1994            404627.906591  449749.870748  
1995            423730.993018  470983.232341  
1996            423268.165074  470468.792273  
1997            478560.649191  531927.201789

In [17]:
import numpy as np

def chain_ladder_method(cumulative_losses):
    # Initialize an empty array for development factors
    development_factors = np.zeros_like(cumulative_losses, dtype=float)

    # Compute development factors
    for i in range(cumulative_losses.shape[0]):
        for j in range(1, cumulative_losses.shape[1]):
            if cumulative_losses[i, j-1] > 0:
                development_factors[i, j] = cumulative_losses[i, j] / cumulative_losses[i, j-1]

    # Compute average development factors
    avg_factors = np.mean(development_factors[:, 1:], axis=0)  # Exclude the first column

    # Project future losses using the average development factors
    projected_losses = np.zeros_like(cumulative_losses, dtype=float)
    for i in range(cumulative_losses.shape[0]):
        projected_losses[i, 1:] = cumulative_losses[i, 0] * np.cumprod(avg_factors)

    return projected_losses

# Example: Create a 10x10 matrix of cumulative losses
cumulative_losses_matrix = np.array([
    [100, 200, 300, 400, 500, 600, 700, 800, 900, 1000],
    [150, 250, 350, 450, 550, 650, 750, 850, 950, 1050],
    [120, 220, 320, 420, 520, 620, 720, 820, 920, 1020],
    [200, 300, 400, 500, 600, 700, 800, 900, 1000, 1100],
    [180, 280, 380, 480, 580, 680, 780, 880, 980, 1080],
    [250, 350, 450, 550, 650, 750, 850, 950, 1050, 1150],
    [300, 400, 500, 600, 700, 800, 900, 1000, 1100, 1200],
    [180, 280, 380, 480, 580, 680, 780, 880, 980, 1080],
    [150, 250, 350, 450, 550, 650, 750, 850, 950, 1050],
    [200, 300, 400, 500, 600, 700, 800, 900, 1000, 1100]
])

# Apply the Chain Ladder method
projected_losses_matrix = chain_ladder_method(cumulative_losses_matrix)

# Display the results
print("Cumulative Losses Matrix:")
print(cumulative_losses_matrix)
print("\nProjected Losses Matrix using Chain Ladder:")
print(projected_losses_matrix)


Cumulative Losses Matrix:
[[ 100  200  300  400  500  600  700  800  900 1000]
 [ 150  250  350  450  550  650  750  850  950 1050]
 [ 120  220  320  420  520  620  720  820  920 1020]
 [ 200  300  400  500  600  700  800  900 1000 1100]
 [ 180  280  380  480  580  680  780  880  980 1080]
 [ 250  350  450  550  650  750  850  950 1050 1150]
 [ 300  400  500  600  700  800  900 1000 1100 1200]
 [ 180  280  380  480  580  680  780  880  980 1080]
 [ 150  250  350  450  550  650  750  850  950 1050]
 [ 200  300  400  500  600  700  800  900 1000 1100]]

Projected Losses Matrix using Chain Ladder:
[[   0.          160.11111111  218.8912963   277.24333623  335.40042684
   393.45181016  451.43931093  509.38520878  567.30248248  625.1992123 ]
 [   0.          240.16666667  328.33694444  415.86500435  503.10064026
   590.17771525  677.1589664   764.07781317  850.95372372  937.79881845]
 [   0.          192.13333333  262.66955556  332.69200348  402.48051221
   472.1421722   541.72717312  611.2